/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzaorder;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Felhasználó
 */
public class PizzaOrder extends javax.swing.JFrame {

    /**
     * Creates new form PizzaOrder
     */
    public PizzaOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MeretBtmG = new javax.swing.ButtonGroup();
        MeretPnl = new javax.swing.JPanel();
        MeretRbt1 = new javax.swing.JRadioButton();
        MeretRbt2 = new javax.swing.JRadioButton();
        MeretRbt3 = new javax.swing.JRadioButton();
        Megsebtn = new javax.swing.JButton();
        Rendelbtn = new javax.swing.JButton();
        PizzaAlapcob = new javax.swing.JComboBox<>();
        Feltetekpnl = new javax.swing.JPanel();
        SonkaCkb = new javax.swing.JCheckBox();
        PaprikaCkb = new javax.swing.JCheckBox();
        Sajtckb = new javax.swing.JCheckBox();
        Kukoricackb = new javax.swing.JCheckBox();
        Szalamickb = new javax.swing.JCheckBox();
        Dbpnl = new javax.swing.JPanel();
        dbAddlbl = new javax.swing.JLabel();
        DbSpin = new javax.swing.JSpinner();
        InformacioPnl = new javax.swing.JPanel();
        NevTf = new javax.swing.JTextField();
        NevLbl = new javax.swing.JLabel();
        TelefonLbl = new javax.swing.JLabel();
        telefonTF = new javax.swing.JTextField();
        Cimlbl = new javax.swing.JLabel();
        CimTF = new javax.swing.JTextField();
        FizetesMLbl = new javax.swing.JLabel();
        FizetesMCb = new javax.swing.JComboBox<>();
        BGImg_Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MeretPnl.setBackground(new java.awt.Color(102, 102, 102));
        MeretPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Méretek"));
        MeretPnl.setForeground(new java.awt.Color(255, 255, 255));

        MeretRbt1.setBackground(new java.awt.Color(102, 102, 102));
        MeretBtmG.add(MeretRbt1);
        MeretRbt1.setSelected(true);
        MeretRbt1.setText("32 Cm");

        MeretRbt2.setBackground(new java.awt.Color(102, 102, 102));
        MeretBtmG.add(MeretRbt2);
        MeretRbt2.setText("50 Cm");

        MeretRbt3.setBackground(new java.awt.Color(102, 102, 102));
        MeretBtmG.add(MeretRbt3);
        MeretRbt3.setText("60 Cm");

        javax.swing.GroupLayout MeretPnlLayout = new javax.swing.GroupLayout(MeretPnl);
        MeretPnl.setLayout(MeretPnlLayout);
        MeretPnlLayout.setHorizontalGroup(
            MeretPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MeretPnlLayout.createSequentialGroup()
                .addGroup(MeretPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MeretRbt1)
                    .addComponent(MeretRbt2)
                    .addComponent(MeretRbt3))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        MeretPnlLayout.setVerticalGroup(
            MeretPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MeretPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MeretRbt1)
                .addGap(18, 18, 18)
                .addComponent(MeretRbt2)
                .addGap(18, 18, 18)
                .addComponent(MeretRbt3)
                .addContainerGap())
        );

        getContentPane().add(MeretPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 100, -1));

        Megsebtn.setBackground(new java.awt.Color(153, 153, 153));
        Megsebtn.setText("Mégse");
        Megsebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MegsebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Megsebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        Rendelbtn.setBackground(new java.awt.Color(153, 153, 153));
        Rendelbtn.setText("Rendelés");
        Rendelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RendelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Rendelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        PizzaAlapcob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---> Válasz alapot ! <---", "        Paradicsomos", "        Fokhagymás" }));
        getContentPane().add(PizzaAlapcob, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 160, 20));

        Feltetekpnl.setBackground(new java.awt.Color(102, 102, 102));
        Feltetekpnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Feltételek"));

        SonkaCkb.setBackground(new java.awt.Color(102, 102, 102));
        SonkaCkb.setText("Sonka");

        PaprikaCkb.setBackground(new java.awt.Color(102, 102, 102));
        PaprikaCkb.setText("Paprika");

        Sajtckb.setBackground(new java.awt.Color(102, 102, 102));
        Sajtckb.setText("Sajt");

        Kukoricackb.setBackground(new java.awt.Color(102, 102, 102));
        Kukoricackb.setText("Kukorica");

        Szalamickb.setBackground(new java.awt.Color(102, 102, 102));
        Szalamickb.setText("Szalámi");

        javax.swing.GroupLayout FeltetekpnlLayout = new javax.swing.GroupLayout(Feltetekpnl);
        Feltetekpnl.setLayout(FeltetekpnlLayout);
        FeltetekpnlLayout.setHorizontalGroup(
            FeltetekpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeltetekpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FeltetekpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SonkaCkb)
                    .addComponent(PaprikaCkb)
                    .addComponent(Sajtckb)
                    .addComponent(Kukoricackb)
                    .addComponent(Szalamickb))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        FeltetekpnlLayout.setVerticalGroup(
            FeltetekpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeltetekpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SonkaCkb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaprikaCkb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sajtckb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kukoricackb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Szalamickb)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(Feltetekpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 130, 160));

        Dbpnl.setBackground(new java.awt.Color(102, 102, 102));

        dbAddlbl.setText("DB");

        DbSpin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout DbpnlLayout = new javax.swing.GroupLayout(Dbpnl);
        Dbpnl.setLayout(DbpnlLayout);
        DbpnlLayout.setHorizontalGroup(
            DbpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DbpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbAddlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DbSpin, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        DbpnlLayout.setVerticalGroup(
            DbpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DbpnlLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(DbpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbAddlbl)
                    .addComponent(DbSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(Dbpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 130, 40));

        InformacioPnl.setBackground(new java.awt.Color(102, 102, 102));
        InformacioPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Informáciok"));

        NevTf.setBackground(new java.awt.Color(153, 153, 153));

        NevLbl.setText("Név :");

        TelefonLbl.setText("TSzám :");

        telefonTF.setBackground(new java.awt.Color(153, 153, 153));

        Cimlbl.setText("Cím :");

        CimTF.setBackground(new java.awt.Color(153, 153, 153));

        FizetesMLbl.setText("Fízetés Mod :");

        FizetesMCb.setBackground(new java.awt.Color(153, 153, 153));
        FizetesMCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--->Válaszon ! <---", "Kézpénz", "Kártya" }));

        javax.swing.GroupLayout InformacioPnlLayout = new javax.swing.GroupLayout(InformacioPnl);
        InformacioPnl.setLayout(InformacioPnlLayout);
        InformacioPnlLayout.setHorizontalGroup(
            InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacioPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformacioPnlLayout.createSequentialGroup()
                        .addGroup(InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cimlbl)
                            .addComponent(TelefonLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(InformacioPnlLayout.createSequentialGroup()
                        .addComponent(NevLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformacioPnlLayout.createSequentialGroup()
                        .addComponent(NevTf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InformacioPnlLayout.createSequentialGroup()
                        .addGroup(InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CimTF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(InformacioPnlLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(FizetesMLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformacioPnlLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(FizetesMCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        InformacioPnlLayout.setVerticalGroup(
            InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacioPnlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NevTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NevLbl))
                .addGap(18, 18, 18)
                .addGroup(InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonLbl)
                    .addComponent(telefonTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InformacioPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cimlbl)
                    .addComponent(CimTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FizetesMLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FizetesMCb, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(InformacioPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 230));

        BGImg_Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/background.PNG"))); // NOI18N
        getContentPane().add(BGImg_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RendelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RendelbtnActionPerformed
        boolean vanfizetesM = FizetesMCb.getSelectedIndex() > 0;
        boolean vanAlap = PizzaAlapcob.getSelectedIndex() > 0;
        boolean NincsNev = NevTf.getText().equals("");
        boolean NincsTszam = telefonTF.getText().equals("");
        boolean NincsCim = CimTF.getText().equals("");
        int ikon = 0;
        String uzenet = "";
        String cim = "";
        JOptionPane.showMessageDialog(null, "Teszt", "Teszt", JOptionPane.WARNING_MESSAGE);
        if (vanAlap & vanfizetesM & !NincsNev & !NincsTszam & !NincsCim) {
            informaciok();
        } else if (!vanfizetesM) {
            ikon = JOptionPane.WARNING_MESSAGE;
            uzenet = "Nincs kiválasztva a Fizetés Mod!";
            cim = "Nincs Fizetés mod!";
        } else if (!vanAlap) {
            ikon = JOptionPane.WARNING_MESSAGE;
            uzenet = "Nincs kiválasztva alap!";
            cim = "Nincs alap!";
        } else if (NincsNev) {
            ikon = JOptionPane.WARNING_MESSAGE;
            uzenet = "Nincs név megadva!";
            cim = "Nincs Név!";
        } else if (NincsTszam) {
            ikon = JOptionPane.WARNING_MESSAGE;
            uzenet = "Nincs Telefon szám megadva!";
            cim = "Nincs telefon szám!";
        } else if (NincsCim) {
            ikon = JOptionPane.WARNING_MESSAGE;
            uzenet = "Nincs cím megadva!";
            cim = "Nincs cím!";
        }

        JOptionPane.showMessageDialog(null, uzenet, cim, ikon);
    }//GEN-LAST:event_RendelbtnActionPerformed

    private void MegsebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MegsebtnActionPerformed
        JOptionPane.showMessageDialog(null, "Visszlát!");
        System.exit(0);
    }//GEN-LAST:event_MegsebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGImg_Lbl;
    private javax.swing.JTextField CimTF;
    private javax.swing.JLabel Cimlbl;
    private javax.swing.JSpinner DbSpin;
    private javax.swing.JPanel Dbpnl;
    private javax.swing.JPanel Feltetekpnl;
    private javax.swing.JComboBox<String> FizetesMCb;
    private javax.swing.JLabel FizetesMLbl;
    private javax.swing.JPanel InformacioPnl;
    private javax.swing.JCheckBox Kukoricackb;
    private javax.swing.JButton Megsebtn;
    private javax.swing.ButtonGroup MeretBtmG;
    private javax.swing.JPanel MeretPnl;
    private javax.swing.JRadioButton MeretRbt1;
    private javax.swing.JRadioButton MeretRbt2;
    private javax.swing.JRadioButton MeretRbt3;
    private javax.swing.JLabel NevLbl;
    private javax.swing.JTextField NevTf;
    private javax.swing.JCheckBox PaprikaCkb;
    private javax.swing.JComboBox<String> PizzaAlapcob;
    private javax.swing.JButton Rendelbtn;
    private javax.swing.JCheckBox Sajtckb;
    private javax.swing.JCheckBox SonkaCkb;
    private javax.swing.JCheckBox Szalamickb;
    private javax.swing.JLabel TelefonLbl;
    private javax.swing.JLabel dbAddlbl;
    private javax.swing.JTextField telefonTF;
    // End of variables declaration//GEN-END:variables

    private int informaciok() {
        String Cim = "Rendelés";
        String RendInf = "Meg Rendelt Pizzárol : ";
        String nev = NevTf.getText();
        String telefon = telefonTF.getText();
        String cim = CimTF.getText();
        String feltet = feltetek();
        String meret = meret();
        int db = (int) DbSpin.getValue();
        String format = String.format("%s\nRendelő neve: %s\nTelefon Szám: %s\nKiszálítási cím: %s\nFeltétek a pizzára: %s\nKiválasztot Méret: %s\nRendelt mennyiség: %d", RendInf, nev, telefon, cim, feltet, meret, db);
        int valasz = JOptionPane.showConfirmDialog(rootPane, format, Cim, JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (valasz == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if (valasz == JOptionPane.NO_OPTION) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new PizzaOrder().setVisible(true);
                }
            });
        }
        return valasz;
    }

    private String feltetek() {
        Boolean[] feltetek = {SonkaCkb.isSelected(), PaprikaCkb.isSelected(), Sajtckb.isSelected(), Kukoricackb.isSelected(), Szalamickb.isSelected()};
        String[] feltetekNeve = {"sonka ", "paprika ", "sajt ", "kukorica ", "szalámi"};
        String txt = "";
        for (int i = 0; i < feltetek.length; i++) {
            if (feltetek[i]) {
                txt += feltetekNeve[i];
            }
        }
        return txt;
    }

    private String meret() {
        String txt = "";
        for (Enumeration<AbstractButton> buttons = MeretBtmG.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }

        return txt;

    }

}
